# SPDX-FileCopyrightText: 2022 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

changelog:
  exclude:
    labels:
      - wontfix
      - duplicate
      - invalid
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Tooling changes
      labels:
        - tooling
    - title: Dependency updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
